"""add file_path and profile_summary to resumes

Revision ID: be3c66542af8
Revises: f4261eea836f
Create Date: 2026-07-05 17:15:10.703746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3c66542af8'
down_revision: Union[str, None] = 'f4261eea836f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('filepath', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('profile_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'profile_summary')
    op.drop_column('resumes', 'filepath')
    # ### end Alembic commands ###
